# Generated by Django 4.0 on 2022-01-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='id',
            new_name='userId',
        ),
    ]
