# Generated by Django 4.0 on 2022-01-31 04:17

from django.db import migrations, models
import posts.spots.models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=posts.spots.models._post_image_upload_to, verbose_name='イメージ画像'),
        ),
    ]
